all:
  hosts:
        10.0.10.116:

  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_cloudinit_k3s
    ansible_python_interpreter: /usr/bin/python3
