- name: "create vyos vm in proxmox hosts"
  hosts: "all"
  vars_prompt:
    - name: pv_password
      prompt: "Node Password"
      private: yes
  user: root@pam
  gather_facts: true
  roles:
    - { role: prepare_vyos_cloud_init_data_for_vms }
    - { role: create_vm }
    - { role: import_disk_to_vm }
