- name: 'stop vms on proxmox'
  hosts: 'all'
  vars_prompt:
  - name: pv_password
    prompt: "Node Password"
    private: yes
  user: root@pam
  gather_facts: true
  roles:
    - { role: start_or_stop_vms, action: stopped } #started, stopped, absent
