---
# Common role
- name: Check if vm exists.
  shell: A=$(qm list | grep {{ item.name }} | grep {{ item.id }}); if [ ! -z "$A" ]; then echo "exists"; fi
  register: vm_exists_state
  with_items: "{{ vms }}"
